- name: add python 2.7 ppa
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7' state=present update_cache=yes

- name: install common python packages
  apt: name=$item state=present update_cache=yes
  with_items:
    - libpq-dev
    - python2.7
    - libxml2-dev
    - zlib1g-dev
    - python-dev
    - python-setuptools
    - python-imaging
    - python-mysqldb
    - python-psycopg2
    - supervisor
    - libmysqlclient-dev
    - libjpeg-dev
    - lib32ncurses5-dev
  tags: packages

- name: build the dependencies of python
  apt: name=python state=build-dep update_cache=yes

- name: install pip 
  easy_install: name=pip state=present

- name: create directory structure
  file: path=/sporple/ state=directory owner=sporple group=sporple mode=0755

- name: pip install virtualenv
  pip: name=virtualenv

- name: create log directory
  file: path={{ log_directory }} state=directory owner=sporple group=sporple mode=0755

- name: copy hosts file
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=0644
